using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MudBlazor.Services;
using Supabase;
using WeatherApp;
using WeatherApp.Services;

var builder = WebAssemblyHostBuilder.CreateDefault(args);

builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

// 🔑 Load config generated by Docker
builder.Configuration.AddJsonFile(
    "appsettings.json",
    optional: false,
    reloadOnChange: false
);

// Services
builder.Services.AddScoped<JsSupabaseAuthService>();
builder.Services.AddScoped<AuthenticatedSupabaseClient>();

builder.Services.AddScoped(sp =>
{
    var config = sp.GetRequiredService<IConfiguration>();

    return new Client(
        config["Supabase:Url"]!,
        config["Supabase:AnonKey"]!,
        new SupabaseOptions
        {
            AutoConnectRealtime = false,
            AutoRefreshToken = true
        }
    );
});

builder.Services.AddSingleton<AuthService>();

builder.Services.AddScoped(sp =>
    new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

builder.Services.AddMudServices();

builder.Services.AddScoped<WeatherService>();
builder.Services.AddScoped<RecentSearchService>();
builder.Services.AddScoped<WeatherHistoryService>();
builder.Services.AddScoped<ProfileStateService>();
builder.Services.AddScoped<FavoriteCityService>();

await builder.Build().RunAsync();
